version: '3.1'

services:
  jogodados:
    container_name: servidordados
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - jogodados
      
networks:
  jogodados:
    driver: bridge